# Generated by Django 3.1.5 on 2021-01-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Appointment_Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100, null=True)),
                ('Email', models.TextField(max_length=70, null=True)),
                ('Phone', models.TextField(max_length=10, null=True)),
                ('Category', models.TextField(max_length=30, null=True)),
                ('Message', models.TextField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Form_Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100, null=True)),
                ('Email', models.TextField(max_length=70, null=True)),
                ('Phone', models.TextField(max_length=10, null=True)),
                ('Category', models.TextField(max_length=30, null=True)),
                ('Message', models.TextField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.TextField(max_length=70, null=True)),
            ],
        ),
    ]
