# Generated by Django 3.1.5 on 2021-01-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_Letter',
        ),
        migrations.RemoveField(
            model_name='book_appointment_events',
            name='Message',
        ),
    ]
